// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSystemInfo():Promise<main.SystemStats>;

export function GetTodos():Promise<Array<main.TodoItem>>;

export function SaveTodos(arg1:Array<main.TodoItem>):Promise<void>;
