// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function SaveTodos(arg1) {
  return window['go']['main']['App']['SaveTodos'](arg1);
}
